import 'dart:async';
String tableNameMachine= 'machine';
String tableNameTanker='tanker';
String tableNameExavation='exavation';
String tableNameFiling='filing';
String tableNameManholes='manholes';
String tableNamePipeline='pipeline';
String tableNameLight='light';
String tableNamePolesExavation='polesExavation';
String tableNamePoles='poles';
String tableNameAsphalt='asphalt';
String tableNameBrick='brick';
String tableNameIron='iron';
String tableNameDrain='drain';
String tableNameSlab='slab';
String tableNamePlaster='plaster';
String tableNameShuttering='shuttering';
String tableNameShifting='shifting';
String tableNameMosque='mosque';
String tableNameNewMaterials='newMaterials';

bool isClockedIn = false;
late Timer timer;
int secondsPassed=0;