// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWsZkiYEe1omz_l6RZDjQfZT6r3eowXBA',
    appId: '1:77601046386:web:909afa52794e6b0694a7eb',
    messagingSenderId: '77601046386',
    projectId: 'townsregistration',
    authDomain: 'townsregistration.firebaseapp.com',
    storageBucket: 'townsregistration.appspot.com',
    measurementId: 'G-XG7F8G7D3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOuwyx0te-GDb58A7pvseyaELYbZH_HFI',
    appId: '1:77601046386:android:e1807b8d8245272c94a7eb',
    messagingSenderId: '77601046386',
    projectId: 'townsregistration',
    storageBucket: 'townsregistration.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiXthWBKQy1DcogiTp87VQbXqFS04_Hnc',
    appId: '1:77601046386:ios:b3ef7d07ce3bc19794a7eb',
    messagingSenderId: '77601046386',
    projectId: 'townsregistration',
    storageBucket: 'townsregistration.appspot.com',
    iosBundleId: 'com.metaxperts.alNoorTown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiXthWBKQy1DcogiTp87VQbXqFS04_Hnc',
    appId: '1:77601046386:ios:b3ef7d07ce3bc19794a7eb',
    messagingSenderId: '77601046386',
    projectId: 'townsregistration',
    storageBucket: 'townsregistration.appspot.com',
    iosBundleId: 'com.metaxperts.alNoorTown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWsZkiYEe1omz_l6RZDjQfZT6r3eowXBA',
    appId: '1:77601046386:web:7d68b19dd5ecd1ef94a7eb',
    messagingSenderId: '77601046386',
    projectId: 'townsregistration',
    authDomain: 'townsregistration.firebaseapp.com',
    storageBucket: 'townsregistration.appspot.com',
    measurementId: 'G-RGXT7QN9HR',
  );
}
